import "./globals.css";
import Header from "../components/Header";
import LogoWa from "../components/ui/LogoWa";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="overflow-x-hidden ">
        <Header />
        {children}
        <LogoWa />
        <Footer />
      </body>
    </html>
  );
}
